name: spark-job-ci-dev

on:
  # Triggers the workflow on push or pull request events for branches starting with "dev-"
  push:
    branches: [ "main" ]

  # Allows manual execution of the workflow from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      app: eureka  # Define the app variable

    steps:
      # Checkout the repository
      - name: Checkout the code
        uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.app }}:dev-${{ github.sha }} .

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.app }}:dev-${{ github.sha }}

  # Job to copy the manifest file to the manifests repository with the appname-manifest.yml nomenclature
  copymanifest:
    needs: build
    runs-on: ubuntu-latest

    env:
      app: eureka  # Define the app variable

    steps:
      # Checkout the current repository (code repository)
      - name: Checkout the code repository
        uses: actions/checkout@v4

      # Checkout the manifests repository
      - name: Checkout the manifests repository
        uses: actions/checkout@v4
        with:
          repository: 'hermann225-zrouama/manifests'
          token: ${{ secrets.PAT_TOKEN }}
          path: spark

      # Copy the deployment.yaml file to the manifests repository with the appname-manifest.yml nomenclature
      - name: Copy manifest file
        run: |
          # Copy and rename the manifest.yml to appname-manifest.yml
          cp manifest.yml spark/${{ env.app }}-manifest.yml
          ls -la

      # Commit and push the manifest changes to the manifests/spark repository
      - name: Commit and push manifest changes
        run: |
          cd spark
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add ${{ env.app }}-manifest.yml
          git commit -m 'Copied manifest to replace or create ${{ env.app }}-manifest.yml by GitHub Actions'
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

  modifygit:
    needs: copymanifest
    runs-on: ubuntu-latest

    env:
      app: eureka  # Define the app variable

    steps:
      # Checkout the repository from GitHub
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          repository: 'hermann225-zrouama/manifests'
          token: ${{ secrets.PAT_TOKEN }}
          path: spark

      # Modify the image in appname-manifest.yml
      - name: Modify the image in appname-manifest.yml
        run: |
          # Configure Git with a generic name and email for GitHub Actions bot
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

          # Update the image reference in appname-manifest.yml with the app variable
          sed -i "s+image: .*$+image: ${{ secrets.DOCKER_USERNAME }}/${{ env.app }}:dev-${{ github.sha }}+g" ${{ env.app }}-manifest.yml

          # Stage and commit changes
          git add ${{ env.app }}-manifest.yml
          git commit -m 'Updated image to ${{ secrets.DOCKER_USERNAME }}/${{ env.app }}:dev-${{ github.sha }} by GitHub Actions'

          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
